### ISSUE TITLE
Default config faulty

### ISSUE THREAD

**Issue by IzKuipers** [IzK-ArcOS/ArcOS-API-Rewritten#6]
The ArcAPI v2 default configuration has invalid parameters:
- `Config.storage.filesystem` should be `"filesystem"` by default, not `null`;
- `Config.storage.template` should be `null` by default, not `"template"`.

Ivan has pointed out this as being a mistake already, this issue is just for bookkeeping.

The default `Config.storage` should be:
```yaml
storage:
  root: "data"
  database: "arcos.sqlite"
  filesystem: "filesystem"
  template: null # to disable templates set this to `null`
```
